# Generated by Django 5.0.4 on 2024-05-03 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estadoSolicitud', models.CharField(choices=[('cancelada', 'Cancelada'), ('aprobada', 'Oferta aprobada'), ('en_espera', 'En espera oferta'), ('creada', 'Oferta creada'), ('finalizada', 'Finalizado')], max_length=50)),
                ('fecha', models.DateField(default=None)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
            ],
        ),
    ]
